recipe: default.v1
assistant_id: 20250928-210406-plain-surface
language: en

pipeline:
  - name: WhitespaceTokenizer
  
  # Feature extraction
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  
  # Text featurization with both word and character levels
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2 
    
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2 
    max_ngram: 4
    
  # Core classifier
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    entity_recognition: true
    intent_classification: true
    use_masked_language_model: true

  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True
    use_word_boundaries: True
    
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    response_key: text
    constrain_similarities: true
    
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    restrict_rules: true
    check_for_contradictions: true
    
  - name: MemoizationPolicy
    max_history: 5
    
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    transformation_rate: 0.8
    split_entities_by_comma: false
    connection_density: 0.2
    augmentation: 50